### ISSUE TITLE
How to make it work for Firefox or Chrome?

### ISSUE THREAD

**Issue by Kikuchiyo1996** [misa198/octotree-icon-theme#1]
### When I load the zip file, I get an error.
![image](https://user-images.githubusercontent.com/72541282/153544973-e29648cf-8e93-4bee-9d61-a6f2e29bd464.png)

**Comment by misa198** [comment]
Please check the folder containing the manifest.json file ?

![Screen Shot 2022-02-11 at 13 37 50](https://user-images.githubusercontent.com/51451216/153547407-d2dd390b-26bf-40f0-b57c-3118a31d1551.png)

**Comment by Kikuchiyo1996** [comment]
It exists in my folder.Only edge browser can be used normally.
![image](https://user-images.githubusercontent.com/72541282/153549671-e039f650-11cc-4af6-9ff8-59942fb0b0f7.png)

![image](https://user-images.githubusercontent.com/72541282/153549545-e9c60daf-1a12-4296-a7dc-e44bceeebd70.png)

**Comment by misa198** [comment]
I can still install normally on Chrome. I found someone with the same problem as you.
https://www.reddit.com/r/chrome_extensions/comments/j0h3jk/load_unpacked_manifest_file_is_missing_or/

![Screen Recording 2022-02-11 at 14 06 59](https://user-images.githubusercontent.com/51451216/153551447-439c7e85-bf92-4ec8-9f5d-5c1f97e716e6.gif)

**Comment by Kikuchiyo1996** [comment]
Now Google browser can use it normally but Firefox browser still cannot load.
I tried to debug this additional component on Firefox browser to get such an error.I am sorry, I have not eager to find a problem.
![图片](https://user-images.githubusercontent.com/72541282/153817017-3a59a507-4fd6-4c1c-8ea9-77c688ae91bc.png)
Here is the problem I found on Stack-overflow.
![图片](https://user-images.githubusercontent.com/72541282/153817437-37407aeb-7720-400d-bfbf-94cc8024b6b6.png)

**Comment by misa198** [comment]
Sorry. This extension is not for Firefox.

**Comment by Kikuchiyo1996** [comment]
Oh.What a shame!Thank you for your answer.

**Comment by misa198** [comment]
Hello. I have rewritten some parts to make this extension work on Firefox. You can download from Firefox add-ons store [here](https://addons.mozilla.org/vi/firefox/addon/octotree-icon-theme/).

**Comment by Kikuchiyo1996** [comment]
> Hello. I have rewritten some parts to make this extension work on Firefox. You can download from Firefox add-ons store [here](https://addons.mozilla.org/vi/firefox/addon/octotree-icon-theme/).

That's cool!Thanks!
